name: iVentoy
package: cloud.lazycat.app.iventoy
version: 1.0.21
min_os_version: 1.3.8
description: iVentoy 是 PXE 服务器的增强版本
homepage: https://iventoy.com/cn/index.html
author: iventoy
application:
    subdomain: iventoy
    background_task: true
    public_path:
        - /

    upstreams:
        - location: /
          backend: http://host.lzcapp:26000/

    ingress:
        - protocol: tcp
          port: 16000
          service: iVentoy
        - protocol: tcp
          port: 10809
          service: iVentoy
        - protocol: udp
          port: 69
          service: iVentoy
services:
    iVentoy:
        # czyt/iventoy:1.0.21
        image: registry.lazycat.cloud/czyt/czyt/iventoy:5d176740a98fdfe2
        binds:
            - /lzcapp/var/data:/iventoy/data
            - /lzcapp/var/user:/iventoy/user
            - /lzcapp/var/iso:/iventoy/iso
        network_mode: host
        setup_script: |
            if [ ! -f /lzcapp/var/data/iventoy.dat ];then
                cp /lzcapp/pkg/content/iventoy.dat /lzcapp/var/data/
            else
                echo "iventoy.dat already exists"
            fi
            if [ ! -f /lzcapp/var/data/mac.db ];then
                cp /lzcapp/pkg/content/mac.db /lzcapp/var/data
            else
                echo "mac.db already exists"
            fi
            if [ ! -d /lzcapp/var/user/scripts ];then
                cp -r /lzcapp/pkg/content/user/scripts /lzcapp/var/user
            else
                echo "example scripts already exists"
            fi
